### PR TITLE
Modify metadata

### PR DESCRIPTION
**Pull request by v-xuto**
Remove invalid slug `prompty`.
For more details, you can click link: https://github.com/MicrosoftDocs/samples/blob/main/Azure-Samples/contoso-chat/.samples-status.json.

@cassiebreviu  and @hemarina for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@cassiebreviu Could you help review this PR? If it looks good to you, please help merge it.

**Comment by v-xuto** [comment]
@cassiebreviu Could you help review this PR? If it looks good to you, please help merge it.

**Review by jongio — APPROVED** [review]

**Comment by cassiebreviu** [comment]
Prompty should stay in the list. Closing request.

**Comment by cassiebreviu** [comment]
@hemarina You can go ahead and request to get it added to resolve the issue. Thanks!

**Comment by v-xuto** [comment]
> @v-xuto Could you initialize the request for adding `prompty` slug?

@hemarina I have submitted the [request](https://forms.office.com/Pages/ResponseDetailPage.aspx?id=v4j5cvGGr0GRqy180BHbR2nL7Pre4mhHrDLxmhrkmOhUQ1BLNVRJN08wQkI4SEdVSkU3QTVZSVpLSSQlQCN0PWcu&rid=186&GetResponseToken=1ovlvnm5nQaEwK9I2TuQKmwfQvQo4KcT7ux43Hes6rQ) for prompty slug and am awaiting the result.

**Pull request closed without merging**
